# Generated by Django 6.0 on 2026-03-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('PERDIDO', 'Perdido'), ('ENCONTRADO', 'Encontrado')], max_length=10)),
                ('raza', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('datos_contacto', models.TextField()),
            ],
        ),
    ]
