# Generated by Django 6.0 on 2026-03-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('OTRO', 'Otro')], default='PERRO', max_length=20, verbose_name='Tipo de Animal'),
        ),
    ]
