# Generated by Django 6.0 on 2026-03-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0003_mascota_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='¿Aprobado para publicar?'),
        ),
    ]
