# Generated by Django 6.0 on 2026-03-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0004_mascota_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tiene_chip',
            field=models.BooleanField(default=False, verbose_name='¿Tiene Chip?'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacunas',
            field=models.BooleanField(default=False, verbose_name='¿Vacunado?'),
        ),
    ]
