# Generated by Django 6.0.3 on 2026-04-06 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0005_mascota_latitud_mascota_longitud_mascota_tiene_chip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='longitud',
        ),
    ]
