# Generated by Django 6.0.3 on 2026-04-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0006_remove_mascota_latitud_remove_mascota_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteHallazgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_evidencia', models.ImageField(upload_to='hallazgos/')),
                ('comentario', models.TextField()),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False, verbose_name='¿Es verídico?')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='mascotas.mascota')),
            ],
        ),
    ]
